// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwaG4Ay3P5xORt2CFlqzs-7bplr37mTX0',
    appId: '1:546044287964:android:374114e0faf1a313d24d19',
    messagingSenderId: '546044287964',
    projectId: 'todo-list-provider-a115d',
    storageBucket: 'todo-list-provider-a115d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3VKWpulh6pYZpSEp4aPpcjVD94D6ObJ8',
    appId: '1:546044287964:ios:bf334eaab94fe55ad24d19',
    messagingSenderId: '546044287964',
    projectId: 'todo-list-provider-a115d',
    storageBucket: 'todo-list-provider-a115d.appspot.com',
    androidClientId: '546044287964-dij2hb276mrm8c7rq35n91t91c6dgvfn.apps.googleusercontent.com',
    iosClientId: '546044287964-g7jvp36fe130p8b9ib27qqnlq5fsmvto.apps.googleusercontent.com',
    iosBundleId: 'br.com.devclassricardo.todoListProvider',
  );
}
